preprocess:
    path: data/heart.csv
    processed_path: cleaned
    file_type: csv
    target: target
train:
    train_path: cleaned/train_cleaned.csv
    target: target
prediction:
    model: artifacts/best_model_RandomForest.h5
    data: cleaned/train_cleaned.csv
    